apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: edge-device-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: ed-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: telegraf-service
    app.kubernetes.io/managed-by: kustomize
  name: telegraf-service
  namespace: ed-system