apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
  namespace: ed-system
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/eds/influxdb-data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-config
  namespace: ed-system
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/eds/influxdb-config"
  persistentVolumeReclaimPolicy: Retain