services:

  ## main
  opc-ua-agent:
    image: docker.io/golang:1.24.2
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app/opc-ua-agent
    environment:
      CONSUMER_TOPIC: "device/config"
      DEVICE_ID: "abc123"
      LOG_LEVEL: "debug"
      BROKER_URL: "tcp://172.31.212.236:31883"

  opc-node-1:
    build:
      context: .
      dockerfile: Dockerfile.server

networks:
  default:
    name: opc-dev