services:
  camera001:
    build:
      context: ./camera
      dockerfile: Dockerfile
    environment:
      DEVICE_PY_BROKER_HOST: 172.31.212.236
      DEVICE_PY_DEVICE_ID: cc0001
      DEVICE_PY_AWS_S3_ENDPOINT: http://minio:9000
      DEVICE_PY_AWS_DEFAULT_REGION: us-east-1
      DEVICE_PY_AWS_BUCKET_NAME: ia-imagens-injetora
  
  injector001:
    build:
      context: ./plc
      dockerfile: Dockerfile
    environment:
      CAPT_FREQUENCY: 100
      DEVICE_ID: ff0001
      DEVICE_PARENT_ID: dd0001
      DEVICE_PARENT_URL: "opc.tcp://dell-g15:4840"
      
networks:
  default:
    name: devices