apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
  namespace: ed-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb    
    spec:
      priorityClassName: default-service
      containers:
      - name: influxdb
        image: influxdb
        ports:
          - containerPort: 8086
        volumeMounts:
          - name: influxdb-data
            mountPath: /var/lib/influxdb2
          - name: influxdb-config
            mountPath: /etc/influxdb2
        livenessProbe:
          exec:
            command:
              - influx
              - ping
          initialDelaySeconds: 10
          periodSeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data-pvc
        - name: influxdb-config
          persistentVolumeClaim:
            claimName: influxdb-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: ed-system
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  namespace: ed-system
spec:
  storageClassName: ""
  volumeName: influxdb-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config-pvc
  namespace: ed-system
spec:
  volumeName: influxdb-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


