apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: operator-service
value: 10001
globalDefault: false
description: "Used by operator"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: default-service
value: 10000
globalDefault: false
description: "Used by default services"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: iot-agent
value: 9999
globalDefault: false
description: "Used by iot-agent"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: simple-service
value: 1
globalDefault: true
description: "Used for another services"