apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: operator
  namespace: ed-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: controller-manager
      containers:
      - name: operator
        image: ed-operator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"