apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-agg
  labels:
    app: telegraf-agg
  namespace: ed-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-agg
  template:
    metadata:
      labels:
        app: telegraf-agg
    spec:
      priorityClassName: default-service
      containers:
      - name: telegraf-agg
        image: telegraf-agg
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"