services:

  ## main
  opc-ua-agent:
    image: docker.io/golang:1.24.2
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app/opc-ua-agent
      - ./../../.certs:/certs
    environment:
      CONSUMER_TOPIC: "device/config/opc"
      DEVICE_ID: "abc123"
      LOG_LEVEL: "debug"
      BROKER_URL: "tcp://172.31.212.236:31883"
      
networks:
  default:
    name: opc-dev